server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    max-threads: 300
    min-spare-threads: 20
# 日志配置
logging:
  level:
    com.tuyou: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: 127.0.0.1
    #数据库索引
    database: 0
    port: 6379
    #密码，默认无
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout:
  devtools:
    restart:
      enabled: true
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.tuyou
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml